"use strict";

(() => {
  const cfg = window.PROFILE_CONFIG;
  const $ = id => document.getElementById(id);
  const els = { form:$("profileForm"), canvas:$("previewCanvas"), status:$("status"), warnings:$("warnings"), download:$("downloadButton"), clear:$("clearButton"), remember:$("remember"), overlay:$("loadingOverlay"), layout:document.querySelector(".layout"), fallback:$("fallback"), fallbackImage:$("fallbackImage"), debug:$("debugPanel"), debugOutput:$("debugOutput") };
  if (!cfg || !els.form || !els.canvas) { document.body.textContent = "必要な設定または画面要素を読み込めませんでした。"; return; }
  const ctx = els.canvas.getContext("2d");
  const state = { background:null, portrait:null, portraitUrl:"", raf:0, ready:false, drawing:false, debug:new URLSearchParams(location.search).get("debug")==="1", debugPoint:null, warnings:new Set() };

  function create(tag, props={}, text="") { const el=document.createElement(tag); Object.entries(props).forEach(([k,v])=>k==="class"?el.className=v:el.setAttribute(k,v)); if(text) el.textContent=text; return el; }
  function fieldById(id){ return cfg.fields.find(f=>f.id===id); }
  function buildTextField(field) {
    const box=create("div",{class:"field"}); const label=create("label",{for:field.id},field.label);
    const counter=create("span",{class:"counter",id:`${field.id}Counter`},`0 / ${field.maxLength}`); label.append(counter); box.append(label);
    const input=create(field.type==="select"?"select":field.multiline?"textarea":"input",{id:field.id,name:field.id,placeholder:field.placeholder,maxlength:field.maxLength});
    if(field.type==="select"){for(let value=field.min;value<=field.max;value++)input.append(create("option",{value},String(value)));}
    else if(!field.multiline){ input.type=field.type; if(field.min!=null) input.min=field.min; if(field.max!=null) input.max=field.max; input.inputMode=field.type==="number"?"numeric":"text"; }
    box.append(input); return box;
  }
  function buildPortraitFields(container) {
    const box=create("div",{class:"field image-controls"}); const label=create("label",{for:"portrait",class:"wide"},"にがおえ・アイコン画像（PNG、JPEG、WebP）");
    const input=create("input",{id:"portrait",type:"file",accept:"image/png,image/jpeg,image/webp",class:"wide"}); box.append(label,input);
    [["portraitScale","拡大率",1,3,.05,1],["portraitX","左右位置",-1,1,.01,0],["portraitY","上下位置",-1,1,.01,0]].forEach(([id,label,min,max,step,value])=>{
      const row=create("div",{class:"range-row wide"}); const lab=create("label",{for:id,class:"range-label"},label); const range=create("input",{id,type:"range",min,max,step,value}); const out=create("output",{id:`${id}Value`,for:id,class:"range-value"},String(value)); row.append(lab,range,out); box.append(row);
    }); box.append(create("button",{id:"removePortrait",type:"button",class:"remove-image wide"},"選択した画像を削除")); container.append(box);
  }
  function buildStats(container) { ["STR","INT","VIT","DEX","AGI"].forEach(id=>appendStatSelect(container,id.toLowerCase(),id)); }
  function appendStatSelect(container,id,label) { const row=create("div",{class:"field range-row"}); row.append(create("label",{for:id,class:"range-label"},label),create("select",{id,name:id})); const select=row.querySelector("select"); for(let i=1;i<=5;i++){const option=create("option",{value:i},String(i)); if(i===3)option.selected=true;select.append(option)} container.append(row); }
  function buildForm() { cfg.sections.forEach((section,index)=>{const details=create("details"); if(index===0)details.open=true; const summary=create("summary",{},`${index+1}. ${section.title}`); const fields=create("div",{class:"fields"}); section.fields.forEach(id=>{if(id==="portrait")buildPortraitFields(fields); else if(id==="str")buildStats(fields); else if(id==="customstat")appendStatSelect(fields,"customstat","自由能力の値"); else {const field=fieldById(id); if(field)fields.append(buildTextField(field));} }); details.append(summary,fields); els.form.append(details); }); }
  function getValues() { const values={}; cfg.fields.forEach(f=>values[f.id]=($(f.id)?.value||"").trim()); cfg.radar.labels.forEach(id=>values[id.toLowerCase()]=Number($(id.toLowerCase())?.value||3)); values.portraitScale=Number($("portraitScale")?.value||1); values.portraitX=Number($("portraitX")?.value||0); values.portraitY=Number($("portraitY")?.value||0); return values; }
  function scheduleDraw() { if(!state.ready||state.raf)return; state.raf=requestAnimationFrame(()=>{state.raf=0; drawCanvas(true);}); }
  function setStatus(message,error=false){els.status.textContent=message; els.status.classList.toggle("error",error);}
  function loadBackground(){return new Promise((resolve,reject)=>{const img=new Image(); img.onload=()=>{state.background=img;els.canvas.width=img.naturalWidth;els.canvas.height=img.naturalHeight;state.ready=true;els.overlay.hidden=true;els.download.disabled=false;setStatus(`準備ができました（元画像 ${img.naturalWidth} × ${img.naturalHeight}px）`);scheduleDraw();resolve();};img.onerror=()=>{els.overlay.textContent="背景画像を読み込めませんでした。";setStatus("エラー：assets/profile-sheet.png を読み込めませんでした。",true);reject(new Error("background"));};img.src="assets/profile-sheet.png";});}
  function pxBox(f){return{x:f.x*els.canvas.width,y:f.y*els.canvas.height,w:f.width*els.canvas.width,h:f.height*els.canvas.height,p:f.padding*els.canvas.width};}
  const forbiddenStart=/^[、。，．！？!?)）】」』]/;
  function wrapText(text,maxWidth,context){const lines=[]; for(const paragraph of String(text).split("\n")){if(paragraph===""){lines.push("");continue} let line=""; for(const char of [...paragraph]){const trial=line+char;if(line&&context.measureText(trial).width>maxWidth){if(forbiddenStart.test(char)&&line.length>1){lines.push(line.slice(0,-1));line=line.slice(-1)+char}else{lines.push(line);line=char}}else line=trial;} lines.push(line);} return lines;}
  function fitText(field,text,box){let size=field.fontSize*els.canvas.width, min=field.minFontSize*els.canvas.width, spacing=field.lineHeight; let lines=[]; while(size>=min){ctx.font=`700 ${size}px ${cfg.fontFamily}`;lines=field.multiline?wrapText(text,box.w-box.p*2,ctx):[text]; const maxW=Math.max(0,...lines.map(l=>ctx.measureText(l).width)); if(maxW<=box.w-box.p*2&&lines.length*size*spacing<=box.h-box.p*2)return{size,spacing,lines,fits:true}; if(spacing>1.1)spacing=Math.max(1.1,spacing-.05);else size-=Math.max(1,els.canvas.width*.0005);} ctx.font=`700 ${min}px ${cfg.fontFamily}`; lines=field.multiline?wrapText(text,box.w-box.p*2,ctx):[text]; return{size:min,spacing:1.1,lines,fits:Math.max(0,...lines.map(l=>ctx.measureText(l).width))<=box.w-box.p*2&&lines.length*min*1.1<=box.h-box.p*2};}
  function drawSingleLine(field,text,box,fit){ctx.textAlign=field.align;ctx.textBaseline="middle";const x=field.align==="center"?box.x+box.w/2:box.x+box.p;ctx.fillText(text,x,box.y+box.h/2,box.w-box.p*2);}
  function drawMultiline(field,box,fit){ctx.textAlign=field.align;ctx.textBaseline="alphabetic";const lineH=fit.size*fit.spacing,total=fit.lines.length*lineH;let y=field.verticalAlign==="middle"?box.y+(box.h-total)/2+fit.size:box.y+box.p+fit.size;const x=field.align==="center"?box.x+box.w/2:box.x+box.p;fit.lines.forEach(line=>{ctx.fillText(line,x,y);y+=lineH;});}
  function drawPortrait(values){if(!state.portrait)return;const pts=cfg.portrait.points.map(([x,y])=>[x*els.canvas.width,y*els.canvas.height]);ctx.save();ctx.beginPath();pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.clip();const minX=Math.min(...pts.map(p=>p[0])),maxX=Math.max(...pts.map(p=>p[0])),minY=Math.min(...pts.map(p=>p[1])),maxY=Math.max(...pts.map(p=>p[1]));const w=maxX-minX,h=maxY-minY,img=state.portrait;const iw=img.width||img.naturalWidth,ih=img.height||img.naturalHeight;const scale=Math.max(w/iw,h/ih)*values.portraitScale,dw=iw*scale,dh=ih*scale;const dx=minX+(w-dw)/2+values.portraitX*w/2,dy=minY+(h-dh)/2+values.portraitY*h/2;ctx.drawImage(img,dx,dy,dw,dh);ctx.restore();}
  function drawRadar(values){const {centerX,centerY,radius,labels}=cfg.radar,cx=centerX*els.canvas.width,cy=centerY*els.canvas.height,r=radius*els.canvas.width;ctx.save();ctx.beginPath();labels.forEach((id,i)=>{const a=-Math.PI/2+i*Math.PI*2/labels.length,rr=r*values[id.toLowerCase()]/5,x=cx+Math.cos(a)*rr,y=cy+Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle="rgba(62,131,181,.28)";ctx.strokeStyle=cfg.textColor;ctx.lineWidth=Math.max(2,els.canvas.width*.0015);ctx.fill();ctx.stroke();ctx.restore();}
  function drawDebug(){const w=els.canvas.width,h=els.canvas.height;ctx.save();ctx.lineWidth=Math.max(1,w*.001);ctx.font=`${Math.max(12,w*.008)}px sans-serif`;cfg.fields.forEach(f=>{const b=pxBox(f);ctx.strokeStyle="#e00062";ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.fillStyle="#e00062";ctx.fillText(f.id,b.x+2,b.y+14)});const pts=cfg.portrait.points.map(([x,y])=>[x*w,y*h]);ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.strokeStyle="#00a060";ctx.stroke();ctx.beginPath();ctx.arc(cfg.radar.centerX*w,cfg.radar.centerY*h,cfg.radar.radius*w,0,Math.PI*2);ctx.strokeStyle="#6c22b8";ctx.stroke();ctx.restore();}
  function drawCanvas(includeDebug=true){if(!state.ready||state.drawing)return;state.drawing=true;state.warnings.clear();const values=getValues();ctx.clearRect(0,0,els.canvas.width,els.canvas.height);ctx.drawImage(state.background,0,0);drawPortrait(values);drawRadar(values);ctx.fillStyle=cfg.textColor;cfg.fields.forEach(f=>{const text=values[f.id];if(!text)return;const box=pxBox(f),fit=fitText(f,text,box);ctx.font=`700 ${fit.size}px ${cfg.fontFamily}`;if(!fit.fits)state.warnings.add(f.label);f.multiline?drawMultiline(f,box,fit):drawSingleLine(f,text,box,fit);});if(state.debug&&includeDebug)drawDebug();els.warnings.textContent=state.warnings.size?`警告：${[...state.warnings].join("、")} は描画枠に収まりきらない可能性があります。入力を短くしてください。`:"";state.drawing=false;}
  async function loadPortrait(file){if(!file)return;if(!/^image\/(png|jpeg|webp)$/.test(file.type)){setStatus("エラー：PNG、JPEG、WebP画像を選択してください。",true);return}try{removePortrait(false);if("createImageBitmap" in window){try{state.portrait=await createImageBitmap(file,{imageOrientation:"from-image"});}catch(_){state.portrait=await createImageBitmap(file);}}else{state.portraitUrl=URL.createObjectURL(file);state.portrait=await new Promise((res,rej)=>{const img=new Image();img.onload=()=>res(img);img.onerror=rej;img.src=state.portraitUrl;});}setStatus("アイコン画像を読み込みました。画像は端末外へ送信されません。");scheduleDraw();}catch(_){setStatus("エラー：選択した画像を読み込めませんでした。",true);}}
  function removePortrait(redraw=true){if(state.portrait?.close)state.portrait.close();if(state.portraitUrl)URL.revokeObjectURL(state.portraitUrl);state.portrait=null;state.portraitUrl="";if($("portrait"))$("portrait").value="";if(redraw)scheduleDraw();}
  function saveLocal(){if(!els.remember.checked)return;const v=getValues();delete v.portraitScale;delete v.portraitX;delete v.portraitY;try{localStorage.setItem(cfg.storageKey,JSON.stringify(v));}catch(_){setStatus("入力内容をこの端末へ保存できませんでした。",true);}}
  function restoreLocal(){try{const raw=localStorage.getItem(cfg.storageKey);if(!raw)return;const v=JSON.parse(raw);Object.entries(v).forEach(([id,value])=>{if($(id))$(id).value=value});els.remember.checked=true;updateCounters();}catch(_){localStorage.removeItem(cfg.storageKey);}}
  function resetInputs(){if(!confirm("入力内容と選択画像をすべて消しますか？"))return;els.form.reset();cfg.radar.labels.forEach(id=>$(id.toLowerCase()).value="3");removePortrait(false);localStorage.removeItem(cfg.storageKey);els.remember.checked=false;updateCounters();setStatus("入力内容を消しました。");scheduleDraw();}
  function updateCounters(){cfg.fields.forEach(f=>{const c=$(`${f.id}Counter`);if(c)c.textContent=`${($(f.id)?.value||"").length} / ${f.maxLength}`});}
  async function savePng(){els.download.disabled=true;const old=els.download.textContent;els.download.textContent="画像を作成中…";try{await document.fonts?.ready;drawCanvas(false);const blob=await new Promise((res,rej)=>els.canvas.toBlob(b=>b?res(b):rej(new Error("blob")),"image/png"));const d=new Date(),pad=n=>String(n).padStart(2,"0"),name=`jaws-profile-${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}.png`;const url=URL.createObjectURL(blob);els.fallbackImage.src=url;els.fallback.hidden=false;const a=create("a",{href:url,download:name});document.body.append(a);a.click();a.remove();setStatus("完成画像を作成しました。ダウンロードされない場合は、下の画像を長押しして保存してください。");setTimeout(()=>URL.revokeObjectURL(url),120000);}catch(_){setStatus("エラー：PNG画像の作成に失敗しました。もう一度お試しください。",true);}finally{els.download.disabled=false;els.download.textContent=old;scheduleDraw();}}
  function updateDebug(event){if(!state.debug)return;const rect=els.canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*els.canvas.width/rect.width,y=(event.clientY-rect.top)*els.canvas.height/rect.height;state.debugPoint={x,y};const hit=cfg.fields.slice().reverse().find(f=>{const b=pxBox(f);return x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h});if(hit&&state.dev){state.dev.fieldSelect.value=hit.id;state.dev.refresh();}els.debugOutput.value=`画像サイズ: ${els.canvas.width} x ${els.canvas.height}\n座標: x ${x.toFixed(1)}, y ${y.toFixed(1)}\n比率: x ${(x/els.canvas.width).toFixed(4)}, y ${(y/els.canvas.height).toFixed(4)}`;scheduleDraw();}
  function buildDeveloperMenu(){
    if(!state.debug||!els.debug)return;
    const original={fontFamily:cfg.fontFamily,fields:cfg.fields.map(f=>({...f})),portrait:{points:cfg.portrait.points.map(point=>[...point])},radar:{centerX:cfg.radar.centerX,centerY:cfg.radar.centerY,radius:cfg.radar.radius}};
    document.body.classList.add("debug-mode");switchTab(true);const toggle=create("button",{type:"button",class:"debug-toggle","aria-expanded":"true"},"調整メニューを小さくする");toggle.addEventListener("click",()=>{const collapsed=els.debug.classList.toggle("collapsed");document.body.classList.toggle("debug-collapsed",collapsed);toggle.textContent=collapsed?"調整メニューを開く":"調整メニューを小さくする";toggle.setAttribute("aria-expanded",String(!collapsed))});els.debug.prepend(toggle);const editor=create("div",{class:"dev-editor"}); editor.append(create("strong",{},"文字配置・フォント調整"));
    const grid=create("div",{class:"dev-grid"});
    const add=(id,label,type="number",attrs={})=>{const lab=create("label",{for:id},label);const input=create(type==="select"?"select":"input",{id,type,...attrs});lab.append(input);grid.append(lab);return input};
    const fieldSelect=add("devField","調整する項目","select"); cfg.fields.forEach(f=>fieldSelect.append(create("option",{value:f.id},`${f.label} (${f.id})`)));
    const fontSelect=add("devFont","描画フォント","select"); [
      [original.fontFamily,"端末標準ゴシック"],['"TanukiMagic", "Yu Gothic", Meiryo, sans-serif',"たぬき油性マジック"],['"Yu Gothic", Meiryo, sans-serif',"游ゴシック"],['Meiryo, sans-serif',"メイリオ"],['"Hiragino Maru Gothic ProN", sans-serif',"ヒラギノ丸ゴ"],['sans-serif',"ブラウザ標準"]
    ].forEach(([v,n])=>fontSelect.append(create("option",{value:v},n)));
    const controls={}; [["x","X比率",0,1,.001],["y","Y比率",0,1,.001],["width","幅比率",.001,1,.001],["height","高さ比率",.001,1,.001],["fontSize","文字サイズ比率",.001,.1,.001],["minFontSize","最小文字比率",.001,.1,.001],["lineHeight","行間",1,2,.05],["padding","余白比率",0,.1,.001]].forEach(([key,label,min,max,step])=>controls[key]=add(`dev-${key}`,label,"number",{min,max,step}));
    controls.align=add("dev-align","横揃え","select"); [["left","左"],["center","中央"],["right","右"]].forEach(([v,n])=>controls.align.append(create("option",{value:v},n)));
    controls.verticalAlign=add("dev-vertical","縦揃え","select"); [["top","上"],["middle","中央"]].forEach(([v,n])=>controls.verticalAlign.append(create("option",{value:v},n)));
    const radarTitle=create("strong",{class:"dev-wide"},"能力値グラフの位置・大きさ");grid.append(radarTitle);const radarControls={};[["centerX","中心X比率",0,1,.001],["centerY","中心Y比率",0,1,.001],["radius","最大半径比率",.001,.25,.001]].forEach(([key,label,min,max,step])=>{const input=add(`dev-radar-${key}`,label,"number",{min,max,step});input.value=cfg.radar[key];input.addEventListener("input",()=>{cfg.radar[key]=Number(input.value);scheduleDraw()});radarControls[key]=input});
    const portraitTitle=create("strong",{class:"dev-wide"},"アイコン切り抜き範囲");grid.append(portraitTitle);const portraitControls=[];["左上","右上","右下","左下"].forEach((name,index)=>{"xy".split("").forEach((axis,axisIndex)=>{const input=add(`dev-portrait-${index}-${axis}`,`${name} ${axis.toUpperCase()}比率`,"number",{min:0,max:1,step:.001});input.value=cfg.portrait.points[index][axisIndex];input.addEventListener("input",()=>{cfg.portrait.points[index][axisIndex]=Number(input.value);scheduleDraw()});portraitControls.push(input)})});
    editor.append(grid); const output=create("textarea",{class:"dev-config",readonly:"",aria_label:"調整済み設定JSON"});
    const refresh=()=>{const f=fieldById(fieldSelect.value);if(!f)return;Object.keys(controls).forEach(k=>controls[k].value=f[k]);output.value=JSON.stringify({fontFamily:cfg.fontFamily,field:{...f}},null,2);scheduleDraw()};
    Object.entries(controls).forEach(([key,input])=>input.addEventListener("input",()=>{const f=fieldById(fieldSelect.value);f[key]=["align","verticalAlign"].includes(key)?input.value:Number(input.value);refresh()}));
    fieldSelect.addEventListener("change",refresh);fontSelect.addEventListener("change",()=>{cfg.fontFamily=fontSelect.value;refresh();if(document.fonts)document.fonts.ready.then(refresh)});
    const actions=create("div",{class:"dev-actions"});const copy=create("button",{type:"button"},"設定をコピー");const reset=create("button",{type:"button"},"初期値に戻す");
    copy.addEventListener("click",async()=>{const all=JSON.stringify({fontFamily:cfg.fontFamily,fields:cfg.fields,portrait:cfg.portrait,radar:cfg.radar},null,2);output.value=all;try{await navigator.clipboard.writeText(all);setStatus("調整した設定をコピーしました。config.jsへ反映できます。")}catch(_){output.select();document.execCommand("copy")}});
    reset.addEventListener("click",()=>{cfg.fontFamily=original.fontFamily;original.fields.forEach((source,i)=>Object.assign(cfg.fields[i],source));cfg.portrait.points=original.portrait.points.map(point=>[...point]);Object.assign(cfg.radar,original.radar);Object.entries(radarControls).forEach(([key,input])=>input.value=cfg.radar[key]);portraitControls.forEach((input,index)=>input.value=cfg.portrait.points[Math.floor(index/2)][index%2]);fontSelect.value=cfg.fontFamily;refresh()});
    actions.append(copy,reset);editor.append(actions,output);els.debug.append(editor);state.dev={fieldSelect,refresh};refresh();
  }  function bind(){els.form.addEventListener("input",e=>{if(e.target.type!=="file"){updateCounters();if(e.target.type==="range")$(`${e.target.id}Value`).textContent=Number(e.target.value).toFixed(e.target.id==="portraitScale"?2:2);saveLocal();scheduleDraw();}});$("portrait").addEventListener("change",e=>loadPortrait(e.target.files[0]));$("removePortrait").addEventListener("click",()=>removePortrait());els.remember.addEventListener("change",()=>{if(els.remember.checked)saveLocal();else localStorage.removeItem(cfg.storageKey)});els.clear.addEventListener("click",resetInputs);els.download.addEventListener("click",savePng);$("inputTab").addEventListener("click",()=>switchTab(false));$("previewTab").addEventListener("click",()=>switchTab(true));els.canvas.addEventListener("click",updateDebug);$("copyDebug").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(els.debugOutput.value);setStatus("デバッグ座標をコピーしました。")}catch(_){els.debugOutput.select();document.execCommand("copy")}});}
  function switchTab(preview){els.layout.classList.toggle("show-preview",preview);$("inputTab").classList.toggle("active",!preview);$("previewTab").classList.toggle("active",preview);$("inputTab").setAttribute("aria-selected",String(!preview));$("previewTab").setAttribute("aria-selected",String(preview));if(preview)scheduleDraw();}
  buildForm();restoreLocal();updateCounters();bind();loadBackground().catch(()=>{});if(state.debug){els.debug.hidden=false;els.debugOutput.value="Canvasをクリックすると座標を表示します。";try{buildDeveloperMenu();}catch(error){console.error("Developer menu initialization failed",error);els.debugOutput.value="開発者メニューの初期化に失敗しました。通常プレビューは引き続き利用できます。";setStatus("開発者メニューの初期化に失敗しました。ページを再読み込みしてください。",true);}}
})();
